phuocng/this-vs-that

client/constants/PostList.ts
client/posts/undefined-vs-void/index.tsx

undefined vs void

---

client/constants/PostList.ts
client/pages/Footer.tsx
client/posts/display-none-vs-hidden-attribute/index.tsx

display: none vs [hidden]

---

client/constants/PostList.ts
client/posts/slice-vs-splice/index.tsx

slice vs splice

---

client/posts/b-i-vs-strong-em/index.tsx

- Fixed 'ans' typo
- Reworded screenreader sentence for improved grammar

Minor spelling/grammar fixes for the '<b>, <i> vs <strong>, <em>' page

---

client/posts/event-prevent-default-vs-return-false/index.tsx

Found little typo in word "false"

Update «event.preventDefault vs return false» page

---

client/constants/PostList.ts
client/posts/undefined-vs-void/index.tsx
client/posts/variable-undefined-vs-typeof-variable-undefined/index.tsx

variable === undefined vs. typeof variable === 'undefined'

---

client/posts/slice-vs-splice/index.tsx

I just made the changes to example to align changes with sentence.

Fixing the original, to align the example with statement made "Now, let's pass the same parameters to slice".

---

client/posts/style-width-vs-width/index.tsx

Also fixed a tiny typo.
❤️ this site, thanks for making it!

Tables support `height=` and `width=` attributes.

---

client/constants/PostList.ts
client/posts/has-own-property-vs-in/index.tsx
client/posts/object-vs-map/index.tsx

Object vs Map

---

client/posts/display-none-vs-opacity-0-vs-visibility-hidden/index.tsx

Fix `opacity` typo in opacity-visibility doc

---

client/constants/PostList.ts
client/posts/function-vs-property-in-interface/index.tsx
client/posts/method-in-class-constructor-vs-prototype/index.tsx

function vs property in interface

---

client/pages/HomePage.tsx
package-lock.json
package.json
tailwind.config.js

Changes: 
- Added hover effect to post boxes
- Updated tailwind to 1.7.0
- Added tailwind variants for group-hover in tailwind.config

Added hover effect

---

client/posts/alt-vs-title/index.tsx
client/posts/style-width-vs-width/index.tsx

Rewording for succinctness and grammar.

Grammar/wording updates for alt-vs-title

---

client/constants/PostList.ts
client/posts/interface-vs-type/index.tsx

interface vs type

---

client/posts/argument-vs-parameter/index.tsx

I hope it's okay to make create a pull request for small typos like that. I'm a big fan of what you built here! Thank you 🙌

Tiny typo in thisthat.dev/argument-vs-parameter

---

client/constants/PostList.ts
client/posts/const-vs-readonly/index.tsx

const vs readonly

---

client/constants/PostList.ts
client/posts/d-ts-vs-ts/index.tsx

*.d.ts vs *.ts

---

client/constants/PostList.ts
client/posts/concat-vs-push/index.tsx

concat vs push

---

client/constants/PostList.ts
client/posts/string-vs-string/index.tsx

string vs String

---

client/constants/PostList.ts
client/posts/literal-union-type-vs-string-enums/index.tsx

literal union type vs string enums

---

client/constants/PostList.ts
client/posts/const-enum-vs-enum/index.tsx
client/posts/literal-union-type-vs-string-enums/index.tsx

const enum vs enum

---

client/constants/PostList.ts
client/posts/map-vs-weak-map/index.tsx
client/posts/object-vs-map/index.tsx

Map vs WeakMap

---

client/constants/PostList.ts
client/posts/event-bubbling-vs-capturing/index.tsx
client/posts/event-prevent-default-vs-return-false/index.tsx
client/posts/stop-immediate-propagation-vs-stop-propagation/index.tsx

event bubbling vs capturing

---

client/constants/PostList.ts
client/pages/HomePage.tsx
client/posts/<->-vs-react-fragment/index.tsx

<> vs <React.Fragment>

---

client/constants/PostList.ts
client/posts/script-async-vs-script-defer/index.tsx

script async vs script defer

---

client/constants/PostList.ts
client/posts/client-height-vs-offset-height-vs-scroll-height/index.tsx
client/posts/client-y-vs-page-y/index.tsx

clientY vs pageY

---

client/constants/PostList.ts
client/posts/function-declaration-vs-function-expression/index.tsx

function declaration vs function expression

---

client/constants/PostList.ts
client/posts/border-box-vs-content-box/index.tsx

border-box vs content-box

---

client/constants/PostList.ts
client/posts/arrow-vs-regular-function/index.tsx

arrow vs regular function

---

client/constants/PostList.ts
client/posts/div-vs-section/index.tsx

<div> vs <section>

---

client/constants/PostList.ts
client/posts/for-in-vs-for-of/index.tsx

for ... in vs for ... of

---

bin/generateSitemap.ts

Fix sitemap

---

client/constants/PostList.ts
client/posts/word-break-break-all-vs-word-wrap-break-word/index.tsx

word-break: break-all vs word-wrap: break-word

---

client/constants/PostList.ts
client/posts/encode-uri-vs-encode-uri-component/index.tsx

encodeURI vs encodeURIComponent

---

client/posts/stop-immediate-propagation-vs-stop-propagation/index.tsx

Just fixing a minor typo. This is a great resource!

addEventListner -> addEventListener

---

client/pages/HomePage.tsx
client/pages/home-page.css

Highlighting already visited topics

---

client/posts/instanceof-vs-typeof/index.tsx

Tweaks to grammar for better readability.

Grammar tweaks

---

posts/event-prevent-default-vs-return-false.md

For those that confused by former/latter it might be more clear if "latter" is changed to "return false".

Fix typo - later to latter

---

posts/postfix-increment-vs-prefix-increment.md

Thank you for creating this great knowledge base. I found just a little grammar issue that I fixed in this PR.
`affect` is a verb, `effect` is a noun.

Grammar fix: effect instead affect

---

contents/number-constructor-vs-parse-int.md

Great resource!
I think that citing Number(undefined) is a good addition, because it is counter-intuitive comparing to others cases.

doc: add counter intuitive Number(undefined)

---

contents/standard-event-handler-vs-event-delegation.mdx

https://phuoc.ng/collection/this-vs-that/standard-event-handler-vs-event-delegation/

feat: standard event handler vs event delegation

---

contents/default-parameters-vs-or-operator.mdx

https://phuoc.ng/collection/this-vs-that/default-parameters-vs-or-operator/

feat: default parameters vs OR operator

---

contents/read-only-vs-read-only-array.mdx

fixes #116 
https://phuoc.ng/collection/this-vs-that/read-only-vs-read-only-array/

feat: Readonly<T[]> vs ReadOnlyArray<T>

---

contents/void-vs-never.mdx

fixes #119 
https://phuoc.ng/collection/this-vs-that/void-vs-never/

feat: void vs never

---

contents/any-vs-unknown.mdx

fixes #114 
https://phuoc.ng/collection/this-vs-that/any-vs-unknown/

feat: any vs unknown

---

contents/keyof-vs-extends-keyof.mdx

fixes #109 
https://phuoc.ng/collection/this-vs-that/keyof-vs-extends-keyof/

feat: keyof vs extends keyof

---

contents/a-vs-not-not-a.mdx
contents/any-vs-unknown.mdx
contents/default-parameters-vs-or-operator.mdx
contents/equality-operator-vs-strict-equality-operator.mdx
contents/keyof-vs-extends-keyof.mdx
contents/number-constructor-vs-parse-int.mdx
contents/read-only-vs-read-only-array.mdx
contents/script-async-vs-script-defer.mdx
contents/standard-event-handler-vs-event-delegation.mdx
contents/void-vs-never.mdx

https://phuoc.ng/collection/this-vs-that/a-vs-not-not-a/

feat: a vs !!a

---

contents/append-vs-append-child.mdx

fixes #220 
https://phuoc.ng/collection/this-vs-that/append-vs-append-child/

feat: append vs appendChild

---

contents/blur-vs-focus-out.mdx

https://phuoc.ng/collection/this-vs-that/blur-vs-focus-out/

feat: blur vs focusOut

---

contents/is-nan-vs-number-is-nan.mdx

https://phuoc.ng/collection/this-vs-that/is-nan-vs-number-is-nan/

feat: isNaN vs Number.isNaN

---

contents/multiple-awaits-vs-promise-all.mdx

https://phuoc.ng/collection/this-vs-that/multiple-awaits-vs-promise-all/

feat: multiple awaits vs Promise.all

---

contents/preload-vs-prefetch.mdx

fixes #204 
https://phuoc.ng/collection/this-vs-that/preload-vs-prefetch/

feat: preload vs prefetch

---

contents/__proto__-vs-prototype.mdx
contents/object-property-with-vs-without-quotes.mdx

fixes #36 
https://phuoc.ng/collection/this-vs-that/__proto__-vs-prototype/

feat: __proto__ vs prototype

---

contents/dev-vs-dev-dependencies-vs-peer-dependencies-in-package-json.mdx

https://phuoc.ng/collection/this-vs-that/dev-vs-dev-dependencies-vs-peer-dependencies-in-package-json/
fixes #137

feat: dev vs devDependencies vs peerDependencies in package.json

---

contents/object-constructor-function-vs-object-literals.mdx

https://phuoc.ng/collection/this-vs-that/object-constructor-function-vs-object-literals/
fixes #39

feat: Object constructor function vs object literals

---

contents/object-property-vs-object-define-property.mdx

https://phuoc.ng/collection/this-vs-that/object-property-vs-object-define-property/
fixes #124

feat: object.property vs Object.defineProperty()

---

contents/set-vs-array.mdx

https://phuoc.ng/collection/this-vs-that/set-vs-array/
fixes #258

feat: Set vs Array

---

contents/eval-vs-new-function.mdx

fixes #254 
https://phuoc.ng/collection/this-vs-that/eval-vs-new-function/

feat: eval vs new Function()

---

contents/object-assign-vs-object-spread-operator.mdx

fixes #259 
https://phuoc.ng/collection/this-vs-that/object-assign-vs-object-spread-operator/

feat: Object.assign() vs Object spread operator

---

contents/deep-copy-vs-shallow-copy.mdx

https://phuoc.ng/collection/this-vs-that/deep-copy-vs-shallow-copy/
fixes #255

feat: Deep copy vs Shallow copy

---

contents/object-freeze-vs-object-seal.mdx

https://phuoc.ng/collection/this-vs-that/object-freeze-vs-object-seal/
fixes #257

feat: Object.freeze() vs Object.seal()

---

contents/pseudo-classes-vs-pseudo-elements.mdx

https://phuoc.ng/collection/this-vs-that/pseudo-classes-vs-pseudo-elements/
fixes #256

feat: pseudo-classes vs pseudo-elements

---

contents/react-node-vs-react-element.mdx

fixes #196 
https://phuoc.ng/collection/this-vs-that/react-node-vs-react-element/

feat: React Node vs React Element

---

contents/node-iterator-vs-tree-walker.mdx

https://phuoc.ng/collection/this-vs-that/node-iterator-vs-tree-walker/
fixes #194

feat: NodeIterator vs TreeWalker

---

contents/call-stack-vs-task-queue.mdx

fixes #190 
https://phuoc.ng/collection/this-vs-that/call-stack-vs-task-queue/

feat: Call stack vs task queue

---

contents/javascript-events-vs-synthetic-react-events.mdx

https://phuoc.ng/collection/this-vs-that/javascript-events-vs-synthetic-react-events/
fixes #185

feat: JavaScript events vs synthetic React events

---

contents/cookie-vs-local-storage-vs-session-storage.mdx

fixes #179 
https://phuoc.ng/collection/this-vs-that/cookie-vs-local-storage-vs-session-storage/

feat: cookie vs localStorage vs sessionStorage

---

contents/set-interval-vs-set-timeout-vs-set-timeout-zero.mdx

https://phuoc.ng/collection/this-vs-that/set-interval-vs-set-timeout-vs-set-timeout-zero/
fixes #136

feat: setInterval() vs setTimeout() vs setTimeout(0)

---

contents/react-use-state-vs-react-use-reducer.mdx

https://phuoc.ng/collection/this-vs-that/react-use-state-vs-react-use-reducer/
fixes #97

feat: React.useState() vs React.useReducer()

---

contents/debouncing-vs-throttling.mdx

https://phuoc.ng/collection/this-vs-that/debouncing-vs-throttling/
fixes #83

feat: Debouncing vs throttling

---

contents/ceil-vs-floor-vs-round.mdx

https://phuoc.ng/collection/this-vs-that/ceil-vs-floor-vs-round/
fixes #38

feat: ceil vs floor vs round

---

contents/animations-and-transitions.mdx

https://phuoc.ng/collection/this-vs-that/animations-and-transitions/
fixes #283

feat: Animations vs Transitions

---

contents/react-create-element-vs-jsx.mdx

https://phuoc.ng/collection/this-vs-that/react-create-element-vs-jsx/
fixes #282

feat: React.createElement() vs JSX

---

contents/anonymous-vs-closure-functions.mdx

fixes #283 
https://phuoc.ng/collection/this-vs-that/anonymous-vs-closure-functions/

feat: Anonymous vs closure functions

---

contents/font-size-vs-line-height.mdx

https://phuoc.ng/collection/this-vs-that/font-size-vs-line-height/
fixes #281

feat: font-size vs line-height

---

contents/children-vs-child-nodes.mdx

fixes #277 
https://phuoc.ng/collection/this-vs-that/children-vs-child-nodes/

feat: children vs childNodes

---

contents/deep-compare-vs-shallow-compare.mdx

https://phuoc.ng/collection/this-vs-that/deep-compare-vs-shallow-compare/
fixes #280

feat: Deep compare vs shallow compare

---

contents/html-entities-vs-unicode-characters.mdx

fixes #279 
https://phuoc.ng/collection/this-vs-that/html-entities-vs-unicode-characters/

feat: HTML entities vs Unicode characters

---

contents/dynamic-vs-static-node-list.mdx

fixes #278 
https://phuoc.ng/collection/this-vs-that/dynamic-vs-static-node-list/

feat: Dynamic vs static NodeList

---

contents/microtasks-vs-macrotasks.mdx

https://phuoc.ng/collection/this-vs-that/microtasks-vs-macrotasks/
fixes #275

feat: Microtasks vs macrotasks

---

contents/react-use-effect-vs-react-use-layout-effect.mdx

fixes #95 
https://phuoc.ng/collection/this-vs-that/react-use-effect-vs-react-use-layout-effect/

feat: React.useEffect() vs React.useLayoutEffect()

---

contents/alt-vs-aria-label.mdx

https://phuoc.ng/collection/this-vs-that/alt-vs-aria-label/

feat: alt vs aria-label

---

contents/controlled-vs-uncontrolled-modes.mdx

https://phuoc.ng/collection/this-vs-that/controlled-vs-uncontrolled-modes/

feat: Controlled vs uncontrolled modes

---

contents/react-create-element-vs-react-clone-element.mdx

https://phuoc.ng/collection/this-vs-that/react-create-element-vs-react-clone-element/

feat: React.createElement() vs React.cloneElement()

---

contents/resize-event-vs-resize-observer.mdx

https://phuoc.ng/collection/this-vs-that/resize-event-vs-resize-observer/

feat: resize event vs ResizeObserver

---

contents/stateless-vs-stateful-components.mdx

https://phuoc.ng/collection/this-vs-that/stateless-vs-stateful-components/

feat: Stateless vs stateful components

---

contents/create-document-fragment-vs-create-element.mdx

https://phuoc.ng/collection/this-vs-that/create-document-fragment-vs-create-element/

feat: createDocumentFragment vs createElement
